//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<facilities> facilities { get; set; }
        public virtual DbSet<phases> phases { get; set; }
        public virtual DbSet<pipes> pipes { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<property_owner> property_owner { get; set; }
        public virtual DbSet<property_type> property_type { get; set; }
        public virtual DbSet<subfacilities> subfacilities { get; set; }
        public virtual DbSet<units> units { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
