//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pipes
    {
        public int id { get; set; }
        public string SpecName { get; set; }
        public Nullable<float> Npd { get; set; }
        public string NpdUnitType { get; set; }
        public Nullable<float> dn { get; set; }
        public string DnUnitType { get; set; }
        public Nullable<float> thickness { get; set; }
        public string ContractorCommodityCode { get; set; }
        public string ShortMaterialDescription { get; set; }
        public string LocalizedShortMaterialDesc { get; set; }
        public string LongMaterialDescription { get; set; }
        public string Vendor { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> FabricationType { get; set; }
        public Nullable<int> SupplyResponsibility { get; set; }
        public Nullable<int> ReportingType { get; set; }
        public Nullable<int> QuantityOfReportableParts { get; set; }
        public Nullable<int> GasketRequirements { get; set; }
        public Nullable<int> BoltingRequirements { get; set; }
        public Nullable<int> ClampRequirement { get; set; }
        public Nullable<int> WeldingRequirement { get; set; }
        public string LooseMaterialRequirements { get; set; }
        public string SubstCapScrewsQuantity { get; set; }
        public string MultiportValveOpReq { get; set; }
        public string ValveOperatorType { get; set; }
        public string ValveOperatorCatalogPartNumber { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
