//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class subfacilities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subfacilities()
        {
            this.units = new HashSet<units>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> facility_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual facilities facilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<units> units { get; set; }
    }
}
